version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
      timezone: Europe/Berlin
    open-pull-requests-limit: 10
    assignees:
      - kai687
