name: Publish a new version on PyPI

on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12
          cache: pip

      - name: Install dependencies
        run: |
          pip install -U pip poetry poetry-plugin-export
          pip --version
          poetry --version
          poetry self show plugins

      - name: Build Packages
        run: |
          poetry build

      - name: Publish to PyPI
        env:
          POETRY_PYPI_TOKEN_PYPI: ${{ secrets.PYPI_TOKEN }}
        run: |
          poetry publish

  tag-release:
    name: Tag release
    runs-on: "ubuntu-latest"
    steps:
      - name: Tag release on GitHub
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          prerelease: false
