name: Run unit tests against different versions of Python and Sphinx

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 3
      matrix:
        python-version: [3.6, 3.7, 3.8]
        sphinx: [20, 21, 22, 23]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Sphinx 2.0.*
        run: pip install sphinx==2.0.*
        if: matrix.sphinx == 20
      - name: Install Sphinx 2.1.*
        run: pip install sphinx==2.1.*
        if: matrix.sphinx == 21
      - name: Install Sphinx 2.2.*
        run: pip install sphinx==2.2.*
        if: matrix.sphinx == 22
      - name: Install Sphinx 2.3.*
        run: pip install sphinx==2.3.*
        if: matrix.sphinx == 23
      - name: Install project dependencies
        run: |
          curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python
          source $HOME/.poetry/env
          poetry install
      - name: Run Pytest
        run: |
          python -c "import sphinx; print(f'Using Sphinx {sphinx.__version__}')"
          poetry run pytest --cov tests --cov-report term
