---
name: Run unit tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8]
        sphinx-version: ["2.*", "3.*"]

    name: Python ${{ matrix.python-version }}, Sphinx ${{ matrix.sphinx-version }}

    steps:
      - uses: actions/checkout@v2
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install nox==2020.5.24
          pip install poetry==1.0.9
          pip install yamllint==1.23.0
      - name: Run nox workflow
        run: |
          nox -p ${{ matrix.python-version }}
